# Generated by Django 5.0.6 on 2024-06-08 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rinconadaParticipations', '0002_remove_admins_clave_admins_password_ciudadanos_curp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participationsdate',
            name='encargado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rinconadaParticipations.admins'),
        ),
        migrations.AlterField(
            model_name='ciudadanos',
            name='cargo',
            field=models.CharField(choices=[('dlg', 'Delegado'), ('cdd', 'Ciudadano'), ('cmn', 'Comunero'), ('vsh', 'Vishcal'), ('tesorero', 'bomberos')], default='cdd', max_length=50),
        ),
        migrations.AlterField(
            model_name='participationsdate',
            name='tipo',
            field=models.CharField(choices=[('f', 'Faenas'), ('p', 'Participaciones'), ('c', 'Coperaciones')], default='f', max_length=50),
        ),
    ]
