# Generated by Django 5.0.6 on 2024-06-08 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rinconadaParticipations', '0003_participationsdate_encargado_alter_ciudadanos_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participationsdate',
            name='encargado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rinconadaParticipations.admins'),
        ),
    ]
