# Generated by Django 5.0.6 on 2025-06-20 16:45

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rinconadaParticipations', '0004_alter_participationsdate_encargado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='participationsdate',
            name='encargado',
            field=models.ForeignKey(limit_choices_to={'cargo': 'dlg'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rinconadaParticipations.ciudadanos'),
        ),
        migrations.AddField(
            model_name='ciudadanos',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 20, 16, 45, 11, 712863, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ciudadanos',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participations',
            name='comentario',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='participations',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 20, 16, 45, 18, 117598, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participations',
            name='estado',
            field=models.CharField(choices=[('confirmada', 'Confirmada'), ('pendiente', 'Pendiente'), ('ausente', 'Ausente')], default='confirmada', max_length=20),
        ),
        migrations.AddField(
            model_name='participations',
            name='evidencia',
            field=models.ImageField(blank=True, null=True, upload_to='evidencias/'),
        ),
        migrations.AlterField(
            model_name='ciudadanos',
            name='cargo',
            field=models.CharField(choices=[('dlg', 'Delegado'), ('cdd', 'Ciudadano'), ('cmn', 'Comunero'), ('vsh', 'Vishcal'), ('tes', 'Tesorero')], default='cdd', max_length=50),
        ),
        migrations.AlterField(
            model_name='ciudadanos',
            name='cedula',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'La cédula debe tener 10 dígitos.')]),
        ),
        migrations.AlterField(
            model_name='ciudadanos',
            name='curp',
            field=models.CharField(blank=True, max_length=18, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{18}$', 'El CURP debe tener 18 caracteres alfanuméricos.')]),
        ),
        migrations.AlterField(
            model_name='ciudadanos',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='ciudadanos',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'El teléfono debe tener 10 dígitos.')]),
        ),
        migrations.AlterField(
            model_name='participationsdate',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='participationsdate',
            name='fecha',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='participationsdate',
            name='tipo',
            field=models.CharField(choices=[('f', 'Faenas'), ('p', 'Participaciones'), ('c', 'Cooperaciones')], default='f', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='participations',
            unique_together={('ciudadano', 'fecha')},
        ),
        migrations.DeleteModel(
            name='Admins',
        ),
    ]
