# Generated by Django 5.0.6 on 2025-06-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rinconadaParticipations', '0005_alter_participationsdate_encargado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudadanos',
            name='cargo',
            field=models.CharField(choices=[('dlg', 'Delegado'), ('cdd', 'Ciudadano'), ('cmn', 'Comunero'), ('vsh', 'Vishcal'), ('tes', 'Tesorero'), ('bmb', 'Bombero')], default='cdd', max_length=50),
        ),
    ]
